{
 "title": "CrowdSec bouncer-mikrotik",
 "tags": [
  "mikrotik",
  "crowdsec"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mikrotik_cmd_total,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mikrotik client error rate",
   "type": "timeseries",
   "description": "Ideally this should be 'no data' or zero",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,result)(increase(mikrotik_client_total{result=\"error\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik client error total",
   "type": "timeseries",
   "description": "Ideally this should be 'no data' or zero, or should not increase over 3h",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,result)(mikrotik_client_total{result=\"error\"})",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik client success total",
   "type": "timeseries",
   "description": "func, operation, result",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,result)(mikrotik_client_total{result=\"success\"})",
     "legendFormat": "{{func}}  {{result}}"
    }
   ]
  },
  {
   "title": "Overview 1h",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,result)(increase(mikrotik_client_total{result=\"success\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{result}}"
    },
    {
     "expr": "sum by (func,result) (increase(mikrotik_client_total{result=\"error\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik command error rate",
   "type": "timeseries",
   "description": "Ideally this should be 'no data' or zero",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(increase(mikrotik_cmd_total{result=\"error\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik command error total",
   "type": "timeseries",
   "description": "Ideally this should be 'no data' or zero, or should not increase over 3h",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(mikrotik_cmd_total{result=\"error\"})",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik FW update success total",
   "type": "timeseries",
   "description": "func, operation, result",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(mikrotik_cmd_total{result=\"success\",func=~\"filter|raw\"})",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Overview 1h",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (increase(decisions_total[$__rate_interval]))",
     "legendFormat": "decisions"
    },
    {
     "expr": "sum (increase(mikrotik_cmd_total{result=\"success\"}[$__rate_interval]))",
     "legendFormat": "mikrotik commands success"
    },
    {
     "expr": "sum (increase(mikrotik_cmd_total{result=\"error\"}[$__rate_interval]))",
     "legendFormat": "mikrotik commands error"
    }
   ]
  },
  { "title": "Mikrotik Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Mikrotik command success - filter update rate",
   "type": "timeseries",
   "description": "func, operation, result",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(increase(mikrotik_cmd_total{result=\"success\",func=~\"filter|raw\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik command success - address_list rate",
   "type": "timeseries",
   "description": "Address inserts to address-list",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(increase(mikrotik_cmd_total{result=\"success\",func=\"address_list\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "MikroTik Command duration rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(increase(mikrotik_cmd_duration_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Lock wait rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(increase(lock_wait_duration_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Mikrotik command success - filter update total",
   "type": "timeseries",
   "description": "func, operation, result",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(mikrotik_cmd_total{result=\"success\",func=~\"filter|raw\"})",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "Mikrotik command success - address_list total",
   "type": "timeseries",
   "description": "Address inserts to address-list",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation,result)(mikrotik_cmd_total{result=\"success\",func=\"address_list\"})",
     "legendFormat": "{{func}} {{operation}} {{result}}"
    }
   ]
  },
  {
   "title": "MikroTik Command duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(mikrotik_cmd_duration_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Lock wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "sum(lock_wait_duration_total)", "legendFormat": "total" }
   ]
  },
  { "title": "Decisions processed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "IPv4 Decisions processed rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (proto,func,operation)(increase(decisions_total{proto=\"ip\"}[$__rate_interval]))",
     "legendFormat": "{{proto}} {{func}} {{operation}}"
    }
   ]
  },
  {
   "title": "IPv6 Decisions processed rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (proto,func,operation)(increase(decisions_total{proto=\"ipv6\"}[$__rate_interval]))",
     "legendFormat": "{{proto}} {{func}} {{operation}}"
    }
   ]
  },
  {
   "title": "IPv4 Truncated TTL rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (proto)(increase(truncated_ttl_total{proto=\"ip\"}[$__rate_interval]))",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "IPv6 Truncated TTL rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (proto)(increase(truncated_ttl_total{proto=\"ipv6\"}[$__rate_interval]))",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  { "title": "Decision Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Cache rate per function/operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation)(increase(cache_count{operation=\"hit\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}}"
    }
   ]
  },
  {
   "title": "Cache rate per function/operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (func,operation)(increase(cache_count{operation!=\"hit\"}[$__rate_interval]))",
     "legendFormat": "{{func}} {{operation}}"
    }
   ]
  },
  { "title": "TTLCache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "TTLCache stats rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation)(increase(ttlcache_stats{operation!=\"hits\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "TTLCache stats rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation)(increase(ttlcache_stats{operation=\"hits\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "TTLCache stats totals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation)(ttlcache_stats{operation!=\"hits\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "TTLCache stats totals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation)(ttlcache_stats{operation=\"hits\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}