name: Build and Publish Container

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read

env:
  BUILDKIT_PROGRESS: plain
  IMAGE_NAME: ${{ github.repository }}
  BASE_VERSION: v0.1 #temporary

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Generate dynamic tags
        id: tags
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          VERSION_TAG="${BASE_VERSION}-g${SHORT_SHA}"
          echo "VERSION_TAG=$VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          sep-tags: ","
          sep-labels: ","
          tags: |
            type=raw,value=${{ env.VERSION_TAG }}
            type=raw,value=latest

      - name: Install ko
        uses: imjasonh/setup-ko@v0.9
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}

      - name: Build and push image with ko
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
          TAGS: ${{ steps.meta.outputs.tags }}
          LABELS: ${{ steps.meta.outputs.labels }}
          PLATFORMS: linux/amd64,linux/arm64,linux/arm
        run: |
          go mod tidy

          PTAGS=$(echo "$TAGS" | sed "s|ghcr.io/${IMAGE_NAME}:||g")
          export SOURCE_DATE_EPOCH=$(date +%s)

          echo "TAGS=$TAGS"
          echo "PTAGS=$PTAGS"
          echo "LABELS=$LABELS"
          echo "PLATFORMS=$PLATFORMS"

          ko build -B --image-label "$LABELS" -t "$PTAGS" --platform=$PLATFORMS .